### ISSUE TITLE
Exception during zip operations: de.schlichtherle.truezip.io.InputException: java.util.zip.ZipException: ??? (expected Local File Header)

### ISSUE THREAD

**Issue by RVanhuysseXenit** [xenit-eu/alfresco-docker-gradle-plugin#72] opened 2019-12-10 13:31 UTC
**Problem**: When trying to build a docker image, the following exception occurs (full stacktrace at alf1 link)

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':apix-docker:docker-61:applyAlfrescoAmp'.
> > 11100015 An error was encountered during deployment of the AMP into the WAR: 11100014 Unable to load module details from property file. File Not Found, /home/red/Documents/code/xenit/alfred-api/apix-impl/61/build/dist/apix-impl-61-2.3.0-local-SNAPSHOT.amp/module.properties
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.6/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 2s
> 20 actionable tasks: 8 executed, 12 up-to-date
> Cause: module.properties (expected Local File Header)
> 14:03:35: Task execution finished 'buildDockerImage'.

**Observations**
* The amp was build with the gradle-sdk v1.0.0
* The amp artifact was referenced as another gradle project int he build.gradle file
* The amp artifact does contain a correct module.properties file
* The problem occurs intermittently, but with unknown cause or solution
* The problem only occurs with alfresco 6.x builds

**resources**
Alf1 folder containing full error log and 2 faulty artifacts: [link](https://alf1.xenit.eu/share/page/folder-details?nodeRef=workspace://SpacesStore/4f479f65-1558-41d1-bedf-f9adf9ead236)

**Comment by RVanhuysseXenit** [comment] 2019-12-10 15:00
ALFREDOPS-406

**Comment by RVanhuysseXenit** [comment] 2019-12-10 15:47
Installing the amp artifact in an appropriate war with the mmt-tool succeeds:
first run is with the alfresco provided war for 6.1, second run is with our own alfresco 6.1.1 war

```red:{}~/Documents/xenit/Problematic amps$ java -jar bin/alfresco-mmt.jar install problemAmps/apix-impl-61-2.3.0-local-SNAPSHOT.amp alfresco.war -verbose
Installing AMP 'problemAmps/apix-impl-61-2.3.0-local-SNAPSHOT.amp' into WAR 'alfresco.war'
Backing up file...
The back up is at '/home/red/Documents/xenit/Problematic amps/alfresco.war-1575992374497.bak'
INFO: Checking the war version using /WEB-INF/classes/alfresco/version.properties
Adding files relating to version '2.3.0-local-SNAPSHOT' of module 'apix-impl-61'
   - File '/WEB-INF/classes/dynamic-extensions/bundles/apix-impl-61-2.3.0-local-SNAPSHOT.jar' added to war from amp
   - File '/WEB-INF/classes/dynamic-extensions/bundles/swagger-ui_5x-1.1.0.jar' added to war from amp
   - Directory '/WEB-INF/classes/dynamic-extensions/bundles' added to war
   - Directory '/WEB-INF/classes/dynamic-extensions' added to war
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/alfresco-global.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/log4j.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/module-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_zh_CN.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_pt_BR.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_fr.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_ja.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_it.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_es.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_nb.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_en.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_ru.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_de.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_nl.properties' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/apix-impl-61/messages' added to war
red:{}~/Documents/xenit/Problematic amps$
red:{}~/Documents/xenit/Problematic amps$ java -jar bin/alfresco-mmt.jar install problemAmps/apix-impl-61-2.3.0-local-SNAPSHOT.amp content-services-6.1.1.war -verbose
Installing AMP 'problemAmps/apix-impl-61-2.3.0-local-SNAPSHOT.amp' into WAR 'content-services-6.1.1.war'
Backing up file...
The back up is at '/home/red/Documents/xenit/Problematic amps/content-services-6.1.1.war-1575992737009.bak'
INFO: Checking the war version using /WEB-INF/classes/alfresco/version.properties
Adding files relating to version '2.3.0-local-SNAPSHOT' of module 'apix-impl-61'
   - File '/WEB-INF/classes/dynamic-extensions/bundles/apix-impl-61-2.3.0-local-SNAPSHOT.jar' added to war from amp
   - File '/WEB-INF/classes/dynamic-extensions/bundles/swagger-ui_5x-1.1.0.jar' added to war from amp
   - Directory '/WEB-INF/classes/dynamic-extensions/bundles' added to war
   - Directory '/WEB-INF/classes/dynamic-extensions' added to war
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/alfresco-global.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/log4j.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/module-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_zh_CN.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_pt_BR.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_fr.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_ja.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_it.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_es.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_nb.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_en.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_ru.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_de.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/apix-impl-61/messages/faceted-search_nl.properties' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/apix-impl-61/messages' added to war
red:{}~/Documents/xenit/Problematic amps$

**Comment by vierbergenlars** [comment] 2020-01-13 15:17
Further investigation in a somewhat reproducible case indicates:
 * This issue is not fixed in 4.1.2
 * Local file header is read from the wrong place, resulting in an exception.

The local file header is `67324752` => `04 03 4B 50`. Because of the endianness conversion, this is `50 4B 03 04` in the file format.

In the hexdump, we can see the header actually starts at `0xac6d`, but truezip attempts to find it at `0xac6a`, which is offset by 3 bytes.

![Screenshot from 2020-01-13 15-55-46](https://user-images.githubusercontent.com/1194648/72266091-f6282900-361d-11ea-9883-85ee61bb3ff0.png)

**Comment by thijslemmens** [comment] 2020-01-17 15:40
workaround: disable the gradle daemon:
--no-daemon

**Comment by vierbergenlars** [comment] 2020-01-19 16:09
How to reproduce:

1. Make sure `org.gradle.daemon=true`, or not set
2. Create a project that builds an AMP with `eu.xenit.amp` and installs that amp inside Alfresco with this plugin
3. Run a build that creates an Alfresco war
4. Modify a file inside the AMP, adding or removing some bytes
5. Run the build again
6. Exception is thrown reliably

**Closed** 2020-01-20 08:55 UTC
Labels: bug, has-jira-ticket
